version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    groups:
      gh-actions-minor-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/app"
      - "/packages/backend"
    schedule:
      interval: "weekly"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"
