version: '3'

services:
  backstage:
    build: .
    ports:
      - 7007:7007
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=technical
      - POSTGRES_PASSWORD=supersecret
    env_file:
      - .env
    depends_on:
      - postgres
    mem_limit: 1024m

  postgres:
    image: postgres:16.3-alpine3.20
    restart: unless-stopped
    mem_limit: 512mb
    environment:
      - POSTGRES_USER=technical
      - POSTGRES_PASSWORD=supersecret
