apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: registry.gitlab.com/whizus/poc/kcd-platform-prototype/kcd_backstage_demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          env:
            - name: POSTGRES_HOST
              value: postgresql-rw
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-app
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-app
                  key: password
            # - name: GITLAB_TOKEN
          imagePullSecrets:
            - name: kcd-demo-app-imagepullsecret
          resources:
            limits:
              cpu: "1"
              memory: 512M
