name: review

on:
  pull_request:
    branches: [main]

jobs:
  reviewdog:
    permissions:
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - name: hadolint
        uses: reviewdog/action-hadolint@73fec8b28091e5082c19df69815dd749d97b882a
        with:
          reporter: github-pr-review
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: markdownlint
        uses: reviewdog/action-markdownlint@28fb4224271253fedd5079b61de820d6228041fd
        with:
          reporter: github-pr-review
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: actionlint
        uses: reviewdog/action-actionlint@7eeec1dd160c2301eb28e1568721837d084558ad
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
