name: review

on:
  pull_request:
    branches: [main]

jobs:
  reviewdog:
    permissions:
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: hadolint
        uses: reviewdog/action-hadolint@2d90b15b2b969e507fc2a31af6e29ca19a0f9516
        with:
          reporter: github-pr-review
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: markdownlint
        uses: reviewdog/action-markdownlint@e9f3ab4fea1433280a4b0eddca17be1340dfea94
        with:
          reporter: github-pr-review
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: tsc
        uses: EPMatt/reviewdog-action-tsc@89934d75ee11d1c298bce81efaa4fde6e00cc21c
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
      - name: actionlint
        uses: reviewdog/action-actionlint@4f8f9963ca57a41e5fd5b538dd79dbfbd3e0b38a
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
